import { QueryInterface } from 'sequelize';

export default {
  up: async (queryInterface: QueryInterface) => {
    await queryInterface.bulkInsert(
      'meals',
      [
        {
            id: 1,
            meal_name: 'Corba',
            meal_category: 'Side',
            meal_area: 'Turkish',
            meal_instructions: 'Pick through your lentils for any foreign debris, rinse them 2 or 3 times, drain, and set aside.  Fair warning, this will probably turn your lentils into a solid block that you’ll have to break up later...\r\nServe with crushed-up crackers, torn up bread, or something else to add some extra thickness. You could also use a traditional thickener (like cornstarch or flour), but I prefer to add crackers for some texture and saltiness. Makes great leftovers, stays good in the fridge for about a week.',
            meal_image: 'https://www.themealdb.com/images/media/meals/58oia61564916529.jpg',
            meal_tag: 'Soup',
            meal_video: 'https://www.youtube.com/watch?v=VVnZd8A84z4',
            meal_ingredient_01: 'Lentils',
            meal_ingredient_02: 'Onion',
            meal_ingredient_03: 'Carrots',
            meal_ingredient_04: 'Tomato Puree',
            meal_ingredient_05: 'Cumin',
            meal_ingredient_06: 'Paprika',
            meal_ingredient_07: 'Mint',
            meal_ingredient_08: 'Thyme',
            meal_ingredient_09: 'Black Pepper',
            meal_ingredient_10: 'Red Pepper Flakes',
            meal_ingredient_11: 'Vegetable Stock',
            meal_ingredient_12: 'Water',
            meal_ingredient_13: 'Sea Salt',
            meal_measure_01: '1 cup ',
            meal_measure_02: '1 large',
            meal_measure_03: '1 large',
            meal_measure_04: '1 tbs',
            meal_measure_05: '2 tsp',
            meal_measure_06: '1 tsp ',
            meal_measure_07: '1/2 tsp',
            meal_measure_08: '1/2 tsp',
            meal_measure_09: '1/4 tsp',
            meal_measure_10: '1/4 tsp',
            meal_measure_11: '4 cups ',
            meal_measure_12: '1 cup ',
            meal_measure_13: 'Pinch',
          },
          {
            id: 2,
            meal_name: 'Burek',
            meal_category: 'Side',
            meal_area: 'Croatian',
            meal_instructions: 'Fry the finely chopped onions and minced meat in oil. Add the salt and pepper. Grease a round baking tray and put a layer of pastry in it. Cover with a thin layer of filling and cover this with another layer of filo pastry which must be well coated in oil. Put another layer of filling and cover with pastry. When you have five or six layers, cover with filo pastry, bake at 200ºC/392ºF for half an hour and cut in quarters and serve.',
            meal_image: 'https://www.themealdb.com/images/media/meals/tkxquw1628771028.jpg',
            meal_tag: 'Streetfood, Onthego',
            meal_video: 'https://www.youtube.com/watch?v=YsJXZwE5pdY',
            meal_ingredient_01: 'Filo Pastry',
            meal_ingredient_02: 'Minced Beef',
            meal_ingredient_03: 'Onion',
            meal_ingredient_04: 'Oil',
            meal_ingredient_05: 'Salt',
            meal_ingredient_06: 'Pepper',
            meal_measure_01: '1 Packet',
            meal_measure_02: '150g',
            meal_measure_03: '150g',
            meal_measure_04: '40g',
            meal_measure_05: 'Dash',
            meal_measure_06: 'Dash',
          },
           {
          id: 3,
          meal_name: 'Sushi',
          meal_category: 'Seafood',
          meal_area: 'Japanese',
          meal_instructions: 'STEP 1\r\nTO MAKE SUSHI ROLLS: Pat out some rice. Lay a nori sheet on the mat, shiny-side down. Dip your hands in the vinegared water, then pat handfuls of rice on top in a 1cm thick layer, leaving the furthest edge from you clear.\r\n\r\nSTEP 2\r\nSpread over some Japanese mayonnaise. Use a spoon to spread out a thin layer of mayonnaise down the middle of the rice.\r\n\r\nSTEP 3\r\nAdd the filling. Get your child to top the mayonnaise with a line of their favourite fillings – here we’ve used tuna and cucumber.\r\n\r\nSTEP 4\r\nRoll it up. Lift the edge of the mat over the rice, applying a little pressure to keep everything in a tight roll.\r\n\r\nSTEP 5\r\nStick down the sides like a stamp. When you get to the edge without any rice, brush with a little water and continue to roll into a tight roll.\r\n\r\nSTEP 6\r\nWrap in cling film. Remove the mat and roll tightly in cling film before a grown-up cuts the sushi into thick slices, then unravel the cling film.\r\n\r\nSTEP 7\r\nTO MAKE PRESSED SUSHI: Layer over some smoked salmon. Line a loaf tin with cling film, then place a thin layer of smoked salmon inside on top of the cling film.\r\n\r\nSTEP 8\r\nCover with rice and press down. Press about 3cm of rice over the fish, fold the cling film over and press down as much as you can, using another tin if you have one.\r\n\r\nSTEP 9\r\nTip it out like a sandcastle. Turn block of sushi onto a chopping board. Get a grown-up to cut into fingers, then remove the cling film.\r\n\r\nSTEP 10\r\nTO MAKE SUSHI BALLS: Choose your topping. Get a small square of cling film and place a topping, like half a prawn or a small piece of smoked salmon, on it. Use damp hands to roll walnut-sized balls of rice and place on the topping.\r\n\r\nSTEP 11\r\nMake into tight balls. Bring the corners of the cling film together and tighten into balls by twisting it up, then unwrap and serve.',
          meal_image: 'https://www.themealdb.com/images/media/meals/g046bb1663960946.jpg',
          meal_video: 'https://www.youtube.com/watch?v=ub68OxEypaY',
          meal_ingredient_01: 'Sushi Rice',
          meal_ingredient_02: 'Rice wine',
          meal_ingredient_03: 'Caster Sugar',
          meal_ingredient_04: 'Mayonnaise',
          meal_ingredient_05: 'Rice wine',
          meal_ingredient_06: 'Soy Sauce',
          meal_ingredient_07: 'Cucumber',
          meal_measure_01: '300ml ',
          meal_measure_02: '100ml',
          meal_measure_03: '2 tbs',
          meal_measure_04: '3 tbs',
          meal_measure_05: '1 tbs',
          meal_measure_06: '1 tbs',
          meal_measure_07: '1',
        },
        {
          id: 4,
          meal_name: 'Kumpir',
          meal_category: 'Side',
          meal_area: 'Turkish',
          meal_instructions: "If you order kumpir in Turkey, the standard filling is first, lots of butter mashed into the potato, followed by cheese. There’s then a row of other toppings that you can just point at to your heart’s content – sweetcorn, olives, salami, coleslaw, Russian salad, allsorts – and you walk away with an over-stuffed potato because you got ever-excited by the choices on offer.\r\n\r\nGrate (roughly – you can use as much as you like) 150g of cheese.\r\nFinely chop one onion and one sweet red pepper.\r\nPut these ingredients into a large bowl with a good sprinkling of salt and pepper, chilli flakes (optional).",
          meal_image: 'https://www.themealdb.com/images/media/meals/mlchx21564916997.jpg',
          meal_tag: 'SideDish',
          meal_video: 'https://www.youtube.com/watch?v=IEDEtZ4UVtI',
          meal_ingredient_01: 'Potatoes',
          meal_ingredient_02: 'Butter',
          meal_ingredient_03: 'Cheese',
          meal_ingredient_04: 'Onion',
          meal_ingredient_05: 'Red Pepper',
          meal_ingredient_06: 'Red Chile Flakes',
          meal_measure_01: '2 large',
          meal_measure_02: '2 tbs',
          meal_measure_03: '150g',
          meal_measure_04: '1 large',
          meal_measure_05: '1 large',
          meal_measure_06: 'Pinch',
        },
        {
          id: 5,
          meal_name: 'Bistek',
          meal_category: 'Beef',
          meal_area: 'Filipino',
          meal_instructions: "0.\tMarinate beef in soy sauce, lemon (or calamansi), and ground black pepper for at least 1 hour. Note: marinate overnight for best result\r\n1.\tHeat the cooking oil in a pan then pan-fry half of the onions until the texture becomes soft. Set aside\r\n2.\tDrain the marinade from the beef. Set it aside. Pan-fry the beef on the same pan where the onions were fried for 1 minute per side. Remove from the pan. Set aside\r\n3.\tAdd more oil if needed. Saute garlic and remaining raw onions until onion softens.\r\n4.\tPour the remaining marinade and water. Bring to a boil.\r\n5.\tAdd beef. Cover the pan and simmer until the meat is tender. Note: Add water as needed.\r\n6.\tSeason with ground black pepper and salt as needed. Top with pan-fried onions.\r\n7.\tTransfer to a serving plate. Serve hot. Share and Enjoy!\r\n",
          meal_image: 'https://www.themealdb.com/images/media/meals/4pqimk1683207418.jpg',
          meal_video: 'https://www.youtube.com/watch?v=xOQON5_S7as',
          meal_ingredient_01: 'Beef',
          meal_ingredient_02: 'Soy Sauce',
          meal_ingredient_03: 'Lemon',
          meal_ingredient_04: 'Garlic',
          meal_ingredient_05: 'Onion',
          meal_ingredient_06: 'Olive Oil',
          meal_ingredient_07: 'Water',
          meal_ingredient_08: 'Salt',
          meal_measure_01: '1 lb',
          meal_measure_02: '5 tablespoons',
          meal_measure_03: '1',
          meal_measure_04: '3 cloves',
          meal_measure_05: '3 parts ',
          meal_measure_06: '4 tbs',
          meal_measure_07: '1 cup ',
          meal_measure_08: '1 pinch',
        },
        {
            id: 6,
            meal_name: 'Tamiya',
            meal_category: 'Vegetarian',
            meal_area: 'Egyptian',
            meal_instructions: 'Soak the beans in water to cover overnight. Drain. If skinless beans are unavailable, rub to loosen the skins, then discard the skins. Pat the beans dry with a towel.\r\nGrind the beans in a food mill or meat grinder. If neither appliance is available, process them in a food processor but only until the beans form a paste. (If blended too smoothly, the batter tends to fall apart during cooking.) Add the scallions, garlic, cilantro, cumin, baking powder, cayenne, salt, pepper, and coriander, if using. Refrigerate for at least 30 minutes.\r\nShape the bean mixture into 1-inch balls. Flatten slightly and coat with flour.\r\nHeat at least 1½ inches of oil over medium heat to 365 degrees.\r\nFry the patties in batches, turning once, until golden brown on all sides, about 5 minutes. Remove with a wire mesh skimmer or slotted spoon. Serve as part of a meze or in pita bread with tomato-cucumber salad and tahina sauce.',
            meal_image: 'https://www.themealdb.com/images/media/meals/n3xxd91598732796.jpg',
            meal_video: 'https://www.youtube.com/watch?v=mulqW-J3Yy4',
            meal_ingredient_01: 'Broad Beans',
            meal_ingredient_02: 'Spring Onions',
            meal_ingredient_03: 'Garlic Clove',
            meal_ingredient_04: 'Parsley',
            meal_ingredient_05: 'Cumin',
            meal_ingredient_06: 'Baking Powder',
            meal_ingredient_07: 'Cayenne Pepper',
            meal_ingredient_08: 'Flour',
            meal_ingredient_09: 'Vegetable Oil',
            meal_measure_01: '3 cups ',
            meal_measure_02: '6',
            meal_measure_03: '4',
            meal_measure_04: '1/4 cup',
            meal_measure_05: '2 tsp',
            meal_measure_06: '1 tsp ',
            meal_measure_07: '1/2 tsp',
            meal_measure_08: 'Sprinkling',
            meal_measure_09: 'As required',
          },
          {
            id: 7,
            meal_name: 'Kafteji',
            meal_category: 'Vegetarian',
            meal_area: 'Tunisian',
            meal_instructions: 'Peel potatoes and cut into 5cm cubes.\r\nPour 1-2 cm of olive oil into a large pan and heat up very hot. Fry potatoes until golden brown for 20 minutes, turning from time to time. Place on kitchen paper to drain.\r\nCut the peppers in half and remove seeds. Rub a little olive oil on them and place the cut side down on a baking tray. Place them under the grill. Grill until the skin is dark and bubbly. While the peppers are still hot, put them into a plastic sandwich bag and seal it. Take them out after 15 minutes and remove skins.\r\nIn the meantime, heat more olive oil another pan. Peel the onions and cut into thin rings. Fry for 15 minutes until golden brown, turning them often. Add the Ras el hanout at the end.\r\nCut the pumpkin into 5cm cubes and fry in the same pan you used for the potatoes for 10-15 minutes until it is soft and slightly browned. Place on kitchen paper.\r\nPour the remaining olive oil out of the pan and put all the cooked vegetables into the pan and mix. Whisk eggs and pour them over the vegetables. Put the lid on the pan so that the eggs cook. Put the contents of the pan onto a large chopping board, add salt and pepper and chopped and mix everything with a big knife.',
            meal_image: 'https://www.themealdb.com/images/media/meals/1bsv1q1560459826.jpg',
            meal_video: 'https://www.youtube.com/watch?v=-TFf-Zu-xQU',
            meal_ingredient_01: 'Potatoes',
            meal_ingredient_02: 'Olive Oil',
            meal_ingredient_03: 'Green Pepper',
            meal_ingredient_04: 'Onions',
            meal_ingredient_05: 'Ras el hanout',
            meal_ingredient_06: 'Pumpkin',
            meal_ingredient_07: 'Eggs',
            meal_ingredient_08: 'Salt',
            meal_ingredient_09: 'Pepper',
            meal_measure_01: '5 Large',
            meal_measure_02: '2 tbs',
            meal_measure_03: '1',
            meal_measure_04: '5',
            meal_measure_05: '1 tbs',
            meal_measure_06: '500g',
            meal_measure_07: '24 Skinned',
            meal_measure_08: 'Pinch',
            meal_measure_09: 'Pinch',
          },
          {
            id: 8,
            meal_name: 'Lasagne',
            meal_category: 'Pasta',
            meal_area: 'Italian',
            meal_instructions: 'Heat the oil in a large saucepan. Use kitchen scissors to snip the bacon into small pieces, or use a sharp knife to chop it on a chopping board. Add the bacon to the pan and cook for just a few mins until starting to turn golden. Add the onion, celery and carrot, and cook over a medium heat for 5 mins, stirring occasionally, until softened.\r\nAdd the garlic and cook for 1 min, then tip in the mince and cook, stirring and breaking it up with a wooden spoon, for about 6 mins until browned all over.\r\nStir in the tomato purée and cook for 1 min, mixing in well with the beef and vegetables. Tip in the chopped tomatoes. Fill each can half full with water to rinse out any tomatoes left in the can, and add to the pan. Add the honey and season to taste. Simmer for 20 mins.\r\nHeat oven to 200C/180C fan/gas 6. To assemble the lasagne, ladle a little of the ragu sauce into the bottom of the roasting tin or casserole dish, spreading the sauce all over the base. Place 2 sheets of lasagne on top of the sauce overlapping to make it fit, then repeat with more sauce and another layer of pasta. Repeat with a further 2 layers of sauce and pasta, finishing with a layer of pasta.\r\nPut the crème fraîche in a bowl and mix with 2 tbsp water to loosen it and make a smooth pourable sauce. Pour this over the top of the pasta, then top with the mozzarella. Sprinkle Parmesan over the top and bake for 25–30 mins until golden and bubbling. Serve scattered with basil, if you like.',
            meal_image: 'https://www.themealdb.com/images/media/meals/wtsvxx1511296896.jpg',
            meal_video: 'https://www.youtube.com/watch?v=gfhfsBPt46s',
            meal_ingredient_01: 'Olive Oil',
            meal_ingredient_02: 'Bacon',
            meal_ingredient_03: 'Onion',
            meal_ingredient_04: 'Celery',
            meal_ingredient_05: 'Carrots',
            meal_ingredient_06: 'Garlic',
            meal_ingredient_07: 'Minced Beef',
            meal_ingredient_08: 'Tomato Puree',
            meal_ingredient_09: 'Chopped Tomatoes',
            meal_ingredient_10: 'Honey',
            meal_ingredient_11: 'Lasagne Sheets',
            meal_ingredient_12: 'Creme Fraiche',
            meal_ingredient_13: 'Mozzarella Balls',
            meal_ingredient_14: 'Parmesan Cheese',
            meal_ingredient_15: 'Basil Leaves',
            meal_measure_01: '1 tblsp ',
            meal_measure_02: '2',
            meal_measure_03: '1 finely chopped ',
            meal_measure_04: '1 Stick',
            meal_measure_05: '1 medium',
            meal_measure_06: '2 cloves chopped',
            meal_measure_07: '500g',
            meal_measure_08: '1 tbls',
            meal_measure_09: '800g',
            meal_measure_10: '1 tblsp ',
            meal_measure_11: '500g',
            meal_measure_12: '400ml',
            meal_measure_13: '125g',
            meal_measure_14: '50g',
            meal_measure_15: 'Topping',
          },
          {
            id: 9,
            meal_name: 'Dal Fry',
            meal_category: 'Vegetarian',
            meal_area: 'Indian',
            meal_instructions: 'Wash and soak toor dal in approx. 3 cups of water, for at least one hour. Dal will be double in volume after soaking. Drain the water.\r\nCook dal with 2-1/2 cups water and add salt, turmeric, on medium high heat, until soft in texture (approximately 30 mins) it should be like thick soup.\r\nIn a frying pan, heat the ghee. Add cumin seeds, and mustard seeds. After the seeds crack, add bay leaves, green chili, ginger and chili powder. Stir for a few seconds.\r\nAdd tomatoes, salt, and sugar, stir and cook until tomatoes are tender and mushy.\r\nAdd cilantro and garam masala, cook for about one minute.\r\nPour the seasoning over dal, mix it well, and cook for another minute.\r\nServe with Naan.',
            meal_image: 'https://www.themealdb.com/images/media/meals/wuxrtu1483564410.jpg',
            meal_video: 'https://www.youtube.com/watch?v=J4D855Q9-jg',
            meal_ingredient_01: 'Toor dal',
            meal_ingredient_02: 'Water',
            meal_ingredient_03: 'Salt',
            meal_ingredient_04: 'Turmeric',
            meal_ingredient_05: 'Ghee',
            meal_ingredient_06: 'Chopped tomatoes',
            meal_ingredient_07: 'Cumin seeds',
            meal_ingredient_08: 'Mustard Seeds',
            meal_ingredient_09: 'Bay Leaf',
            meal_ingredient_10: 'Green Chili',
            meal_ingredient_11: 'Ginger',
            meal_ingredient_12: 'Cilantro',
            meal_ingredient_13: 'Red Pepper',
            meal_ingredient_14: 'Salt',
            meal_ingredient_15: 'Sugar',
            meal_ingredient_16: 'Garam Masala',
            meal_measure_01: '1 cup',
            meal_measure_02: '2-1/2 cups',
            meal_measure_03: '1 tsp',
            meal_measure_04: '1/4 tsp',
            meal_measure_05: '3 tbs',
            meal_measure_06: '1 cup',
            meal_measure_07: '1/2 tsp',
            meal_measure_08: '1/2 tsp',
            meal_measure_09: '2',
            meal_measure_10: '1 tbs chopped',
            meal_measure_11: '2 tsp shredded',
            meal_measure_12: '2 tbs ',
            meal_measure_13: '1/2 tsp',
            meal_measure_14: '1/2 tsp',
            meal_measure_15: '1 tsp',
            meal_measure_16: '1/4 tsp',
          },
      ],
          {},
        );
      },
    
      down: async (queryInterface: QueryInterface) => {
        await queryInterface.bulkDelete('meals', {});
      },
    }